# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='marked',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
